services:
  db:
    image: mariadb:10.5
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: yourdbrootpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: yourdbpassword
    volumes:
      - yourdiskpath/docker-data/nextcloud-db:/var/lib/mysql
    networks:
      - mybridge-net
      
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    ports:
      - "8082:80"
    environment:
      PUID: 1001
      PGID: 100
      TZ: America/Sao_Paulo
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: yourdbpassword
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: yourpassword
      NEXTCLOUD_DATA_DIR: /data
    volumes:
      - yourdiskpath/docker-data/nextcloud/config:/config
      - yourdiskpath/nextcloud/data:/data
    depends_on:
      - db
    networks:
      - mybridge-net
    restart: unless-stopped

networks:
  mybridge-net:
    external: true
